name: autooglasnik_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mini.jpg
    - assets/images/mini2.jpg
    - assets/images/mini3.jpg
    - assets/images/mini4.jpg
    - assets/images/mini5.jpg
    - assets/images/mini6.jpg
    - assets/images/mini7.jpg
    - assets/images/mini8.jpg
    - assets/images/mini9.jpg
    - assets/images/mini10.jpg
    - assets/images/mini11.jpg
    - assets/images/mini12.jpg
